  List<String> listaCategora = [
    "Administração e Negócios",
    "Animais de Estimação",
    "Arquitetura e Engenharia",
    "Artes e Música",
    "Auto-ajuda e Desenvolvimento Pessoal",
    "Automóveis",
    "Blogs e Redes Sociais",
    "Casa e Jardinagem",
    "Culinária e Gastronomia",
    "Design e Templates PSD, PPT ou HTML",
    "Edição de Áudio, Vídeo ou Imagens",
    "Educacional, Cursos Técnicos e Profissionalizantes",
    "Eletrodomésticos",
    "Eletrônicos",
    "Eletroportáteis",
    "Entretenimento, Lazer e Diversão",
    "Esportes e Fitness",
    "Filmes e Cinema",
    "Histórias em Quadrinhos",
    "Idiomas",
    "Informática",
    "Internet Marketing",
    "Investimentos e Finanças",
    "Jogos de Cartas, Poker, Loterias",
    "Jogos de Computador, Jogos Online",
    "Jurídico",
    "Literatura e Poesia",
    "Marketing de Rede",
    "Marketing e Comunicação",
    "Meio Ambiente",
    "Moda e vestuário",
    "Moveis e decoração",
    "Música, Bandas e Shows",
    "Paquera, Sedução e Relacionamentos",
    "Perfumaria",
    "Pessoas com deficiência",
    "Plugins, Widgets e Extensões",
    "Produtividade e Organização Pessoal",
    "Produtos infantis",
    "Relatórios, Artigos e Pesquisas",
    "Religião e Crenças",
    "Romances, Dramas, Estórias e Contos",
    "RPG e Jogos de Mesa",
    "Saúde, Bem-estar e Beleza",
    "Segurança do Trabalho",
    "Sexologia e Sexualidade",
    "Turismo"
  ];

  var _listaImagens = [
    "Administracao_Negocios",
    "Animais_Estimacao",
    "Arquitetura_Engenharia",
    "Artes_Musica",
    "Auto_ajuda",
    "Automoveis",
    "Blogs_Sociais",
    "Casa_Jardinagem",
    "Culinaria",
    "Design",
    "Edicao_Imagens",
    "Educacional_Profissionalizantes",
    "Eletrodomesticos",
    "Eletronicos",
    "Eletroportateis",
    "Entretenimento_Diversao",
    "Esportes_Fitness",
    "Filmes_Cinema",
    "Historias",
    "Idiomas",
    "Informatica",
    "Internet_Marketing",
    "Investimentos_Financas",
    "Jogos_Loterias",
    "Jogos_Online",
    "Juridico",
    "Literatura_Poesia",
    "Marketing_Rede",
    "Marketing_Comunicacao",
    "Meio_Ambiente",
    "Moda_vestuario",
    "Moveis_decoracao",
    "Musica_Shows",
    "Paquera_Relacionamentos",
    "Perfumaria",
    "Pessoas_deficiencia",
    "Plugins_Extensoes",
    "Produtividade_Pessoal",
    "Produtos_infantis",
    "Relatorios_Pesquisas",
    "Religião_Crenças",
    "Romances_Contos",
    "RPG_Mesa",
    "Saude_Beleza",
    "Seguranca_Trabalho",
    "Sexologia_Sexualidade",
    "Turismo"
  ];